# Generated by Django 4.2.11 on 2024-04-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_instauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.instauser'),
        ),
    ]
