# Generated by Django 4.2.11 on 2024-04-23 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='post_videos/')),
                ('caption', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.instauser')),
            ],
        ),
    ]
